version: '3'

services:
    
    login_db:
        container_name: login_db
        build:
            context: ./services/login/db
            dockerfile: Dockerfile.dev
        volumes:
            - login_db_data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: mysql_password # default user: root
        ports:
            - 8081:3306 # mysql workbench -> host: localhost:8080, user: root, password: mysql_password 

    password_reset_db:
        container_name: password_reset_db
        build:
            context: ./services/passwordReset/db
            dockerfile: Dockerfile.dev
        volumes:
            - password_reset_db_data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: mysql_password # default user: root
        ports:
            - 8082:3306 # mysql workbench -> host: localhost:8080, user: root, password: mysql_password 

    sms_db:
        container_name: sms_db
        build:
            context: ./services/sms/db
            dockerfile: Dockerfile.dev
        volumes:
            - sms_db_data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: mysql_password # default user: root
        ports:
            - 8083:3306 # mysql workbench -> host: localhost:8080, user: root, password: mysql_password 

    signup:
        container_name: signup
        build:
            context: ./services/signup
            dockerfile: Dockerfile.dev
        ports:
            - 3000:3000
        volumes:
            - /app/node_modules
            - ./services/signup:/app

    login:
        container_name: login
        build:
            context: ./services/login
            dockerfile: Dockerfile.dev
        ports:
            - 3001:3001
        volumes:
            - /app/node_modules
            - ./services/login:/app
        depends_on: 
            - login_db


    password_reset:
        container_name: password_reset
        build:
            context: ./services/passwordReset
            dockerfile: Dockerfile.dev
        ports:
            - 3002:3002
        volumes:
            - /app/node_modules
            - ./services/passwordReset:/app
        depends_on:
            - password_reset_db

    auth:
        container_name: auth 
        build:
            context: ./services/auth
            dockerfile: Dockerfile.dev
        ports:
            - 3003:3003
        volumes:
            - /app/node_modules
            - ./services/auth:/app

    email:
        container_name: email
        build:
            context: ./services/email
            dockerfile: Dockerfile.dev
        ports:
            - 3004:3004
        volumes:
            - /app/node_modules
            - ./services/email:/app
        env_file: 
            - ./services/email/config/dev.env
            
    sms:
        container_name: sms
        build:
            context: ./services/sms
            dockerfile: Dockerfile.dev
        ports:
            - 3005:3005
        volumes:
            - /app/node_modules
            - ./services/sms:/app
        env_file: 
            - ./services/sms/config/dev.env
        depends_on:
            - sms_db

volumes:
    login_db_data:
    sms_db_data:
    password_reset_db_data:   